image: docker:latest

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

stages:
  - build
  - deploy

build_images:
  stage: build
  script:
    - docker-compose build

deploy_server:
  stage: deploy
  script:
    - docker-compose up -d
